name = "plague"
license = "MIT"
licenselink = "https://github.com/brianreumere/plague/blob/main/LICENSE"
description = "A minimal Hugo theme with microformats"
homepage = "https://github.com/brianreumere/plague"
tags = ["blog", "minimal"]
features = ["blog"]
min_version = "0.41.0"

[author]
  name = "brian@mutualaid.info"
  homepage = "https://mutualaid.info"
